chore: bump product-config and stackable-operator version
stackabletech/edc-operator pull request #112
Opened 2024-07-11 13:16 UTC by xeniape

# Description

Part of https://github.com/stackabletech/issues/issues/601, https://github.com/stackabletech/issues/issues/557

## Definition of Done Checklist

- Not all of these items are applicable to all PRs, the author should update this template to only leave the boxes in that are relevant
- Please make sure all these things are done and tick the boxes

```[tasklist]
# Author
- [ ] Changes are OpenShift compatible
- [ ] CRD changes approved
- [ ] CRD documentation for all fields, following the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs-style-guide).
- [ ] Helm chart can be installed and deployed operator works
- [ ] Integration tests passed (for non trivial changes)
- [ ] Changes need to be "offline" compatible
```

```[tasklist]
# Reviewer
- [ ] Code contains useful comments
- [ ] Code contains useful logging statements
- [ ] (Integration-)Test cases added
- [ ] Documentation added or updated. Follows the [style guide](https://docs.stackable.tech/home/nightly/contributor/docs-style-guide).
- [ ] Changelog updated
- [ ] Cargo.toml only contains references to git tags (not specific commits or branches)
```

```[tasklist]
# Acceptance
- [ ] Feature Tracker has been updated
- [ ] Proper release label has been added
- [ ] [Roadmap](https://github.com/orgs/stackabletech/projects/25/views/1) has been updated
```

2024-07-11 15:27 UTC, NickLarsenNZ approved these changes
LGTM

2024-07-11 15:27 UTC, NickLarsenNZ commented on CHANGELOG.md
> +- Bump `stackable-operator` to `0.70.0`, `product-config` to `0.7.0`, and other dependencies  ([#112]).
nit

```suggestion
- Bump `stackable-operator` to `0.70.0`, `product-config` to `0.7.0`, and other dependencies ([#112]).
```

2024-07-12 11:49 UTC, NickLarsenNZ requested changes

2024-07-12 11:49 UTC, NickLarsenNZ commented on Cargo.toml
Just tokio needs bumping to 1.38

2024-07-12 12:01 UTC, xeniape commented on Cargo.toml
Done with https://github.com/stackabletech/edc-operator/pull/112/commits/0caa44697c1ad06d06b8b1f25a0f7812b626b8b1
For some reason Cargo.lock and Cargo.nix already included the version 1.38 :thinking:

2024-07-12 12:55 UTC, NickLarsenNZ commented on Cargo.toml
Yeah because 1.37 is the minimum, and `cargo update` (with out specifying a single crate) should update all. Cargo.nix is built from Cargo.lock.

2024-07-12 12:57 UTC, merged